version: "3.2"
services :
  redis:
   image: 'redis:6.2-alpine'
   restart: always
   ports:
   - "6379:6379"


  node:
    image : xconnected/components:itms-node-cpu-2.0
    command: ./entrypoint.sh
    depends_on :
      - redis
    volumes:
      - /workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ./db:/app/db
    restart: always
    network_mode: host
    environment:
      - DEBUG=0
      - CENTRAL_SERVER_URL=http://10.71.5.3/api-config/
      - CENTERAL_AUTH_URL=http://10.71.5.3/auth/realms/XconnectedAuthentication/protocol/openid-connect/token
      - AUTH_USERNAME=system
      - AUTH_PASSWORD=system@123
      - AUTH_CLIENT_ID=node
      - CLIENT_SECRET=NGEzna22kqqBDaAqj8lvsiEWZ4jhZrNv
      - NETWORK_PREFIX=10.2
      - PROGRAM_LOG_PATH="./log.file"
      - KAFKA_BOOTSTRAP_SERVER=10.71.5.3:9092
      - DOCKER_LOGIN_CLIENT=DOCKERHUB
      - DOCKER_LOGIN_USERNAME=bitvividtac
      - DOCKER_LOGIN_PASSWORD_TOKEN=dckr_pat_pWlLa4Iq9xgtZCc8s_AgHfxy5BA
      - DOWNLOAD_BASE_PATH=''
